# Generated by Django 5.1.4 on 2025-01-12 01:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Auteur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom_aut", models.CharField(max_length=50)),
                ("prenom_aut", models.CharField(max_length=50)),
                ("adr_aut", models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Classification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom_cl", models.CharField(max_length=50)),
                ("prenom_cl", models.CharField(max_length=50)),
                ("num_tel_cl", models.CharField(max_length=50)),
                ("adr_cl", models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Fournisseur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom_four", models.CharField(max_length=50)),
                ("prenom_four", models.CharField(max_length=50)),
                ("num_tel", models.CharField(max_length=50)),
                ("adr_four", models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Livre",
            fields=[
                (
                    "ISBN",
                    models.CharField(max_length=25, primary_key=True, serialize=False),
                ),
                ("titre", models.CharField(max_length=50)),
                ("edition", models.CharField(max_length=50)),
                ("NbrDePages", models.IntegerField(blank=True, null=True)),
                (
                    "classification",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="limsApp.classification",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Emprunter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="limsApp.client"
                    ),
                ),
                (
                    "livre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="limsApp.livre"
                    ),
                ),
            ],
            options={
                "unique_together": {("livre", "client")},
            },
        ),
        migrations.CreateModel(
            name="Ecrire",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "auteur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="limsApp.auteur"
                    ),
                ),
                (
                    "livre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="limsApp.livre"
                    ),
                ),
            ],
            options={
                "unique_together": {("livre", "auteur")},
            },
        ),
        migrations.CreateModel(
            name="Acheter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_achat", models.DateField()),
                ("prix_achat", models.IntegerField()),
                ("quantite_acheter", models.IntegerField(blank=True, null=True)),
                (
                    "fournisseur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="limsApp.fournisseur",
                    ),
                ),
                (
                    "livre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="limsApp.livre"
                    ),
                ),
            ],
            options={
                "unique_together": {("livre", "fournisseur")},
            },
        ),
    ]
